#define PVRSRV_MODULE_BASEDIR "/system/modules/"
#define LINUX 
#define PVR_BUILD_DIR "omap4430_android"
#define PVR_BUILD_TYPE "release"
#define PVRSRV_MODNAME "pvrsrvkm"
#define SGXCORE 540
#define SGX540 
#define SUPPORT_SGX540 
#define SUPPORT_SGX 
#define SGX_CORE_REV 120
#define TRANSFER_QUEUE 
#define PVR_SECURE_HANDLES 
#define USE_PTHREADS 
#define DISPLAY_CONTROLLER omaplfb
#define _XOPEN_SOURCE 600
#define _POSIX_C_SOURCE 199309
#define OPK_DEFAULT "libpvrANDROID_WSEGL_SGX540_120.so"
#define OPK_FALLBACK ""
#define FFGEN_UNIFLEX 
#define SUPPORT_OPENCL 
#define RELEASE 
#define SUPPORT_PERCONTEXT_PB 
#define SUPPORT_HW_RECOVERY 
#define SUPPORT_ACTIVE_POWER_MANAGEMENT 
#define SUPPORT_SGX_HWPERF 
#define SUPPORT_SGX_LOW_LATENCY_SCHEDULING 
#define SUPPORT_MEMINFO_IDS 
#define SUPPORT_SGX_NEW_STATUS_VALS 
#define SUPPORT_DBGDRV_EVENT_OBJECTS 
#define SYS_USING_INTERRUPTS 
#define PVRSRV_NEW_PVR_DPF 
#define PVR2D_ALT_2DHW 
#define PVR2D_VALIDATE_INPUT_PARAMS 
#define SUPPORT_OPENGLES1 
#define SUPPORT_OPENGLES2 
#define SUPPORT_SOURCE_SHADER 
#define SUPPORT_BINARY_SHADER 
#define CLIENT_DRIVER_DEFAULT_WAIT_RETRIES 50
#define API_MODULES_RUNTIME_CHECKED 
#define ANDROID 
#define OGLES1_BASEPATH "/system/lib/egl/"
#define OGLES2_BASEPATH "/system/lib/egl/"
#define OGLES1_BASENAME "GLESv1_CM_POWERVR_SGX540_120"
#define OGLES2_BASENAME "GLESv2_POWERVR_SGX540_120"
#define SUPPORT_GRAPHICS_HAL 
#define SUPPORT_ANDROID_PLATFORM 
#define PVR_ANDROID_NEEDS_ANATIVEWINDOW_TYPEDEF 
#define PVR_ANDROID_NEEDS_ANATIVEWINDOWBUFFER_TYPEDEF 
#define PVR_ANDROID_SURFACE_FIELD_NAME "mSurface"
#define PVR_ANDROID_PLATFORM_HAS_LINUX_FBDEV 
#define PVR_NO_FULL_CACHE_OPS 
