#define LINUX 
#define PVR_BUILD_DIR "omap4430_android"
#define PVR_BUILD_TYPE "release"
#define PVRSRV_MODNAME "pvrsrvkm"
#define SGXCORE 540
#define SGX540 
#define SUPPORT_SGX540 
#define SUPPORT_SGX 
#define SGX_CORE_REV 120
#define TRANSFER_QUEUE 
#define PVR_SECURE_HANDLES 
#define DISPLAY_CONTROLLER omaplfb
#define RELEASE 
#define SUPPORT_PERCONTEXT_PB 
#define SUPPORT_HW_RECOVERY 
#define SUPPORT_ACTIVE_POWER_MANAGEMENT 
#define SUPPORT_SGX_HWPERF 
#define SUPPORT_SGX_LOW_LATENCY_SCHEDULING 
#define SUPPORT_MEMINFO_IDS 
#define SUPPORT_SGX_NEW_STATUS_VALS 
#define SUPPORT_DBGDRV_EVENT_OBJECTS 
#define SYS_USING_INTERRUPTS 
#define PVRSRV_NEW_PVR_DPF 
#define SUPPORT_LINUX_X86_WRITECOMBINE 
#define SUPPORT_LINUX_X86_PAT 
#define SGX_DYNAMIC_TIMING_INFO 
#define SYS_SGX_ACTIVE_POWER_LATENCY_MS 100
#define SYS_CUSTOM_POWERLOCK_WRAP 
#define PVR_LINUX_USING_WORKQUEUES 
#define PVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE 
#define PVR_LINUX_TIMERS_USING_WORKQUEUES 
#define LDM_PLATFORM 
#define PVR_LDM_PLATFORM_PRE_REGISTERED 
#define PVR_LDM_PLATFORM_PRE_REGISTERED_DEV "pvrsrvkm"
#define PVR_LDM_DRIVER_REGISTRATION_NAME "pvrsrvkm"
#define SUPPORT_LARGE_GENERAL_HEAP 
#define ANDROID 
#define PVR_NO_FULL_CACHE_OPS 
#define PVR_NO_OMAP_TIMER 
